[package]
name = "gen-millen"
version = "0.1.0"
authors = ["alexmorley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.13.1"
